use std::process::Command;
use tauri::State;
use std::sync::Mutex;
use serde::{Serialize, Deserialize};

#[derive(Debug, Serialize, Deserialize)]
pub struct RemoteSyncConfig {
    pub host: String,
    pub user: String,
    pub remote_path: String,
    pub port: u16,
}

#[tauri::command]
pub fn sync_to_remote(db_conn: State<Mutex<rusqlite::Connection>>, config: RemoteSyncConfig) -> Result<String, String> {
    // 获取所有主机配置
    let conn = db_conn.lock().unwrap();

    // 获取所有分组
    let mut group_stmt = conn.prepare("SELECT id, name FROM groups").map_err(|e| e.to_string())?;
    let group_iter = group_stmt.query_map([], |row| {
        Ok((row.get::<_, String>(0)?, row.get::<_, String>(1)?))
    }).map_err(|e| e.to_string())?;

    let mut groups: std::collections::HashMap<String, String> = std::collections::HashMap::new();
    for group_result in group_iter {
        if let Ok((id, name)) = group_result {
            groups.insert(id, name);
        }
    }

    // 获取所有主机
    let mut stmt = conn.prepare(
        "SELECT name, host, port, user, auth_type, identity_file, group_id, notes FROM hosts ORDER BY name"
    ).map_err(|e| e.to_string())?;

    let host_iter = stmt.query_map([], |row| {
        let group_id: Option<String> = row.get(6)?;
        let group_name = group_id.as_ref().and_then(|gid| groups.get(gid).cloned());

        Ok((
            row.get::<_, String>(0)?, // name
            row.get::<_, String>(1)?, // host
            row.get::<_, i32>(2)?,    // port
            row.get::<_, String>(3)?, // user
            row.get::<_, String>(4)?, // auth_type
            row.get::<_, Option<String>>(5)?, // identity_file
            group_name,               // group_name
            row.get::<_, Option<String>>(7)?, // notes
        ))
    }).map_err(|e| e.to_string())?;

    let mut hosts = Vec::new();
    for host_result in host_iter {
        hosts.push(host_result.map_err(|e| e.to_string())?);
    }

    // 生成 SSH config 内容
    let mut config_content = String::new();
    config_content.push_str("# SSH Config - Generated by SSH Config Master\n");
    config_content.push_str(&format!("# Generated at {}\n\n", chrono_lite_now()));

    // 按分组组织
    let mut groups_map: std::collections::HashMap<Option<String>, Vec<_>> = std::collections::HashMap::new();
    for host in hosts {
        let key = host.6.clone();
        groups_map.entry(key).or_default().push(host);
    }

    // 写入分组主机
    for (group_name, group_hosts) in &groups_map {
        if let Some(name) = group_name {
            config_content.push_str(&format!("# --- {} ---\n\n", name));
        }
        for (name, host, port, user, _auth_type, identity_file, _, notes) in group_hosts {
            config_content.push_str(&format!("Host {}\n", name));
            config_content.push_str(&format!("    HostName {}\n", host));
            config_content.push_str(&format!("    Port {}\n", port));
            config_content.push_str(&format!("    User {}\n", user));
            if let Some(ref id_file) = identity_file {
                config_content.push_str(&format!("    IdentityFile {}\n", id_file));
            }
            if let Some(ref note) = notes {
                for line in note.lines() {
                    config_content.push_str(&format!("    # {}\n", line));
                }
            }
            config_content.push('\n');
        }
    }

    // 创建临时文件
    let temp_path = std::env::temp_dir().join("ssh_config_sync");
    std::fs::write(&temp_path, &config_content).map_err(|e| format!("写入临时文件失败: {}", e))?;

    // 使用 scp 同步到远程
    let remote_target = format!("{}@{}:{}", config.user, config.host, config.remote_path);
    let port_arg = format!("-P{}", config.port);

    let output = Command::new("scp")
        .arg(&port_arg)
        .arg(&temp_path)
        .arg(&remote_target)
        .output()
        .map_err(|e| format!("执行 scp 失败: {}. 请确保已安装 scp 并配置了 SSH 密钥认证。", e))?;

    // 清理临时文件
    let _ = std::fs::remove_file(&temp_path);

    if output.status.success() {
        Ok(format!("成功同步到 {}@{}:{}", config.user, config.host, config.remote_path))
    } else {
        let stderr = String::from_utf8_lossy(&output.stderr);
        Err(format!("同步失败: {}", stderr))
    }
}

#[tauri::command]
pub fn test_remote_connection(host: String, user: String, port: u16) -> Result<String, String> {
    let output = Command::new("ssh")
        .arg("-p").arg(port.to_string())
        .arg("-o").arg("ConnectTimeout=5")
        .arg("-o").arg("BatchMode=yes")
        .arg(&format!("{}@{}", user, host))
        .arg("echo 'connection_ok'")
        .output()
        .map_err(|e| format!("执行 SSH 测试失败: {}", e))?;

    if output.status.success() {
        Ok("连接成功".to_string())
    } else {
        let stderr = String::from_utf8_lossy(&output.stderr);
        Err(format!("连接失败: {}", stderr))
    }
}

fn chrono_lite_now() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    let hours = (secs % 86400) / 3600;
    let minutes = (secs % 3600) / 60;
    let seconds = secs % 60;
    let mut days = secs / 86400;

    let mut year = 1970u64;
    loop {
        let days_in_year = if year % 4 == 0 && (year % 100 != 0 || year % 400 == 0) { 366u64 } else { 365u64 };
        if days < days_in_year { break; }
        days -= days_in_year;
        year += 1;
    }

    let leap = year % 4 == 0 && (year % 100 != 0 || year % 400 == 0);
    let month_days: [u64; 12] = if leap {
        [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    } else {
        [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    };

    let mut month = 1u64;
    for &md in &month_days {
        if days < md { break; }
        days -= md;
        month += 1;
    }
    let day = days + 1;

    format!("{:04}-{:02}-{:02} {:02}:{:02}:{:02}", year, month, day, hours, minutes, seconds)
}
