use std::fs;
use directories::UserDirs;
use tauri::State;
use std::sync::Mutex;
use std::collections::HashSet;

use super::host_commands::get_hosts;
use super::group_commands::get_groups;

/// Sanitize group name for directory name
fn safe_dirname(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_alphanumeric() || c == '-' || c == '_' { c } else { '_' })
        .collect()
}

/// Generate SSH config block for one host
fn host_block(host: &crate::models::host::HostConfig) -> String {
    let mut s = format!("Host {}\n", host.name);
    s.push_str(&format!("    HostName {}\n", host.host));
    s.push_str(&format!("    User {}\n", host.user));
    s.push_str(&format!("    Port {}\n", host.port));
    if let Some(ref identity_file) = host.identity_file {
        if !identity_file.is_empty() {
            s.push_str(&format!("    IdentityFile {}\n", identity_file));
        }
    }
    s.push('\n');
    s
}

/// Ensure `Include config.d/*` is present at the top of ~/.ssh/config
fn ensure_include_directive(ssh_dir: &std::path::Path) -> Result<(), String> {
    let config_path = ssh_dir.join("config");
    let include_line = "Include config.d/*";

    if config_path.exists() {
        let content = fs::read_to_string(&config_path).map_err(|e| e.to_string())?;
        for line in content.lines() {
            let trimmed = line.trim();
            if trimmed.eq_ignore_ascii_case(include_line) || trimmed.eq_ignore_ascii_case("Include ~/.ssh/config.d/*") {
                return Ok(());
            }
        }
        let new_content = format!("{}\n\n{}", include_line, content);
        fs::write(&config_path, new_content).map_err(|e| e.to_string())?;
    } else {
        fs::write(&config_path, format!("{}\n", include_line)).map_err(|e| e.to_string())?;
    }
    Ok(())
}

/// Clean up stale files/dirs generated by us
fn cleanup_stale(config_d: &std::path::Path, keep_dirs: &HashSet<String>) {
    if !config_d.exists() { return; }
    if let Ok(entries) = fs::read_dir(config_d) {
        for entry in entries.flatten() {
            let name = entry.file_name().to_string_lossy().to_string();
            // Skip if it's a dir we're keeping
            if keep_dirs.contains(&name) { continue; }
            // Remove files we generated (marked with comment)
            if entry.file_type().map(|ft| ft.is_file()).unwrap_or(false) {
                if let Ok(content) = fs::read_to_string(entry.path()) {
                    if content.starts_with("# SSH Config Master") {
                        let _ = fs::remove_file(entry.path());
                    }
                }
            }
        }
    }
}

#[tauri::command]
pub fn sync_ssh_config(db_conn: State<Mutex<rusqlite::Connection>>) -> Result<String, String> {
    let hosts = get_hosts(db_conn.clone())?;
    let groups = get_groups(db_conn)?;

    let user_dirs = UserDirs::new().ok_or("无法获取用户主目录")?;
    let ssh_dir = user_dirs.home_dir().join(".ssh");
    let config_d = ssh_dir.join("config.d");

    // Create directories
    if !ssh_dir.exists() {
        fs::create_dir_all(&ssh_dir).map_err(|e| e.to_string())?;
    }
    if !config_d.exists() {
        fs::create_dir_all(&config_d).map_err(|e| e.to_string())?;
    }

    // Ensure Include directive in ~/.ssh/config
    ensure_include_directive(&ssh_dir)?;

    let mut keep_dirs: HashSet<String> = HashSet::new();
    let mut total_hosts = 0usize;

    // For each group, create a directory with index.conf
    for group in &groups {
        let dir_name = safe_dirname(&group.name);
        keep_dirs.insert(dir_name.clone());

        let group_dir = config_d.join(&dir_name);
        if !group_dir.exists() {
            fs::create_dir_all(&group_dir).map_err(|e| e.to_string())?;
        }

        // All hosts in group (for terminal SSH)
        let all_group_hosts: Vec<_> = hosts.iter()
            .filter(|h| h.group.as_deref() == Some(&group.id))
            .collect();

        if !all_group_hosts.is_empty() {
            let mut content = format!(
                "# SSH Config Master - 分组: {}\n# 此文件由 SSH Config Master 自动生成，请勿手动编辑\n\n",
                group.name
            );
            for host in &all_group_hosts {
                content.push_str(&host_block(host));
            }
            fs::write(group_dir.join("index.conf"), content).map_err(|e| e.to_string())?;
            total_hosts += all_group_hosts.len();
        } else {
            // Remove index.conf if no hosts
            let _ = fs::remove_file(group_dir.join("index.conf"));
        }
    }

    // Ungrouped hosts -> _ungrouped directory
    let ungrouped_dir = "_ungrouped";
    keep_dirs.insert(ungrouped_dir.to_string());
    let ungrouped_path = config_d.join(ungrouped_dir);
    if !ungrouped_path.exists() {
        fs::create_dir_all(&ungrouped_path).map_err(|e| e.to_string())?;
    }

    let ungrouped_hosts: Vec<_> = hosts.iter().filter(|h| h.group.is_none()).collect();
    if !ungrouped_hosts.is_empty() {
        let mut content = "# SSH Config Master - 未分组\n# 此文件由 SSH Config Master 自动生成，请勿手动编辑\n\n".to_string();
        for host in &ungrouped_hosts {
            content.push_str(&host_block(host));
        }
        fs::write(ungrouped_path.join("index.conf"), content).map_err(|e| e.to_string())?;
        total_hosts += ungrouped_hosts.len();
    } else {
        let _ = fs::remove_file(ungrouped_path.join("index.conf"));
    }

    // Clean up stale directories
    cleanup_stale(&config_d, &keep_dirs);

    Ok(format!(
        "同步完成：{} 台主机 -> {}/",
        total_hosts,
        config_d.display()
    ))
}
