use std::fs;
use directories::UserDirs;
use tauri::State;
use std::sync::Mutex;

use super::host_commands::get_hosts;
use super::group_commands::get_groups;

#[tauri::command]
pub fn sync_ssh_config(db_conn: State<Mutex<rusqlite::Connection>>) -> Result<String, String> {
    let hosts = get_hosts(db_conn.clone())?;
    let groups = get_groups(db_conn)?;

    let mut config_content = String::from("# Generated by SSH Config Master\n\n");

    // First, write hosts that belong to a group
    for group in &groups {
        let group_hosts: Vec<_> = hosts.iter().filter(|h| h.group.as_deref() == Some(&group.id)).collect();
        if group_hosts.is_empty() { continue; }
        config_content.push_str(&format!("# === {} ===\n", group.name));
        for host in group_hosts {
            config_content.push_str(&format!("Host {}\n", host.name));
            config_content.push_str(&format!("    HostName {}\n", host.host));
            config_content.push_str(&format!("    User {}\n", host.user));
            config_content.push_str(&format!("    Port {}\n", host.port));
            if let Some(identity_file) = &host.identity_file {
                config_content.push_str(&format!("    IdentityFile {}\n", identity_file));
            }
            config_content.push_str("\n");
        }
    }

    // Then, write hosts that don't belong to any group
    let ungrouped: Vec<_> = hosts.iter().filter(|h| h.group.is_none()).collect();
    if !ungrouped.is_empty() {
        config_content.push_str("# === 未分组 ===\n");
        for host in ungrouped {
            config_content.push_str(&format!("Host {}\n", host.name));
            config_content.push_str(&format!("    HostName {}\n", host.host));
            config_content.push_str(&format!("    User {}\n", host.user));
            config_content.push_str(&format!("    Port {}\n", host.port));
            if let Some(identity_file) = &host.identity_file {
                config_content.push_str(&format!("    IdentityFile {}\n", identity_file));
            }
            config_content.push_str("\n");
        }
    }

    let user_dirs = UserDirs::new().ok_or("Could not find home directory")?;
    let ssh_dir = user_dirs.home_dir().join(".ssh");
    if !ssh_dir.exists() {
        fs::create_dir_all(&ssh_dir).map_err(|e| e.to_string())?;
    }
    let config_path = ssh_dir.join("config");
    fs::write(&config_path, &config_content).map_err(|e| e.to_string())?;

    Ok(format!("已成功同步到 {}", config_path.display()))
}
